### ISSUE TITLE
Problem: Created and Updated times are not imported correctly

### ISSUE THREAD

**Issue by tatrishd** [rpgd60/simplenote2enex#5]
Hi, when I imported data to Evernote using this script on October 22, 2021,
"Created" and "Updated" times on Evernote became the imported time.
As you commented on line 189 in simplenote2joplin.py, I was able to import the "Created" and "Update" times by removing the milliseconds.

```
        created_datetime = datetime.datetime.strptime(sn_note['creationDate'], '%Y-%m-%dT%H:%M:%S.%fZ)
        enex_created = created_datetime.strftime('%Y%m%dT%H%M%SZ')
        updated_datetime = datetime.datetime.strptime(sn_note['lastModified'], '%Y-%m-%dT%H:%M:%S.%fZ)
        enex_updated = updated_datetime.strftime('%Y%m%dT%H%M%SZ')
```

**Comment by rpgd60** [comment]
Hi 
Thank you for your note.I have not looked at this script for ages.   Sorry but I am not sure I understood the problem.  Could you kindly clarify?  (e.g.  you mention that you imported to Evernote,  but this script is meant for Joplin.) 
Cheers

**Comment by tatrishd** [comment]
Oops, I'm sorry.
I just forgot that I was diverting this Joplin script for Evernote and raised an issue.
I hope you forget it.
